### PR TITLE
add alternate data set for testing

### PR DESCRIPTION
**Pull request by jwestgard**
The metadata still has some issues, but this can be used to test the import process.

The file is more than 50MB so runs up against a large file warning, but still comes in under the 100MB limit for a single file.

### CODE REVIEW

**Comment by awoods** [comment]
Was this generated with `/fcr:export`? If so, could you please instead generate a tar file from `/fcr:backup`.
`/fcr:export` and the converse, `/fcr:import` have been deprecated and do not exist in Fedora 4.6.0.

**Comment by awoods** [comment]
Related to: https://jira.duraspace.org/browse/FCREPO-2133

**Comment by jwestgard** [comment]
Yes, fcr:export.  I was trying to get clarification about that on IRC this morning, but unfortunately did not see your message before I had to leave for a meeting. Sorry.  I don't think I can fix this before late pm.

**Comment by jwestgard** [comment]
I have replaced the file with a fcr:backup-generated tar. I tarred the entire directory including the backup, binaries, and changes directories.

**Comment by jwestgard** [comment]
There are still some problems in the metadata (for some metadata rows, the SPARQL update fails so not every item gets updated as it should -- and a few miscellaneous other issues).  Also, I have not yet made the external content references as indicated in the ticket.  I have an idea how to do that, though, and will try to get to that soon.  In the meantime, however, this can be used to test the concept of a bootstrap dataset in this format.

**Comment by awoods** [comment]
As a git recommendation, you may find it safer in the long-term to never work directly on your own local `master` branch.
Before making any updates:
```sh
git checkout -b my-branch
```

**Comment by awoods** [comment]
```sh
gunzip plants.tar.gz 
gzip: plants.tar.gz: not in gzip format
```

**Comment by awoods** [comment]
Although after untarring the data file, and performing:
```sh
 curl -X POST --data-binary "/tmp/awoods/x/data/1472778329972-0" localhost:8080/rest/fcr:restore
```
I get a successful load of 200 resources.

**Comment by jwestgard** [comment]
Thanks for the heads-up regarding the compression. I suspect that is the result of differences in the tar program on Ubuntu vs. Mac.  I will figure it out and (if desired) propose some fuller documentation here: https://wiki.duraspace.org/display/FEDORA40/RESTful+HTTP+API+-+Backup+and+Restore

I think the steps for retrieving those backup files once you've made them will not be obvious to all users, particularly from a guest VM.

**Comment by awoods** [comment]
Let me know if you plan on compressing the data and replacing `plants.tar.gz`. If not, I am happy to do it for you.
Once that is resolved, we can move forward with this dataset.

**Comment by jwestgard** [comment]
I will fix it.

**Comment by jwestgard** [comment]
OK I think this resolves the .zip problem. I think this is probably still the same sub-optimal branch usage, though, which is something I'll need to ponder a bit more.

**Comment by jwestgard** [comment]
As far as I can see, it is too late to squash these four together. I could be missing something.

**Pull request merged**
