### PR TITLE
Local

### PR DESCRIPTION
**Pull request by jwestgard**
This should resolve FCREPO-2166-68.  There are external binaries, directly contained nodes, and other internally related nodes.

### CODE REVIEW

**Comment by jwestgard** [comment]
I'm not sure why there are 5 commits in this pull request since I thought the first 3 or 4 of these had already been merged. Clearly I'm not doing this right.

**Comment by jwestgard** [comment]
I'll give this another go in a separate request.

**Comment by escowles** [comment]
@jwestgard You may need to checkout the master branch and pull the changes to get the commits that were merged.  You can then either rebase your branch, or create a new branch off of master and move your changes there.  Let me know if you want any help doing that.

**Comment by jwestgard** [comment]
@escowles Thanks! I'll give it a try.

**Pull request closed without merging**
